# Generated by Django 3.2.16 on 2023-02-12 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0004_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('drink_1', models.IntegerField()),
                ('drink_2', models.IntegerField()),
                ('drink_3', models.IntegerField()),
                ('drink_4', models.IntegerField()),
                ('drink_6', models.IntegerField()),
                ('drink_7', models.IntegerField()),
                ('person1', models.TextField()),
                ('person2', models.TextField()),
                ('person3', models.TextField()),
                ('person4', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylist.profile_add')),
            ],
        ),
    ]
