# Generated by Django 3.2.16 on 2023-02-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_profile_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('no_test', models.TextField()),
                ('etc', models.TextField()),
                ('error_1', models.TextField()),
                ('error_2', models.TextField()),
                ('error_3', models.TextField()),
                ('error_4', models.TextField()),
                ('error_content', models.TextField()),
                ('error_fix', models.TextField()),
                ('address', models.TextField()),
                ('person1', models.TextField()),
                ('person2', models.TextField()),
                ('person_phone1', models.TextField()),
                ('person3', models.TextField()),
                ('person4', models.TextField()),
                ('person_phone2', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylist.profile')),
            ],
        ),
    ]
